### ISSUE TITLE
Get Chrome extension working in dev mode

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#29]
I can view style guides but can't get tips to get triggered when I check in Gmail.

![image](https://cloud.githubusercontent.com/assets/3891237/22636680/f8a91d5c-ec0a-11e6-96f1-6892de563862.png)

"Get Irregardless Tips" doesn't do anything
![image](https://cloud.githubusercontent.com/assets/3891237/22636691/0b7dbdc0-ec0b-11e6-8302-ee8d33277279.png)

**Comment by tenji240** [comment]
hmm, I gave it a shot in reddit just to test it out and got some tips to pop up, will keep testing across websites to try and pinpoint where an error is occuring.

<img width="1920" alt="chrome-plugin" src="https://cloud.githubusercontent.com/assets/4622414/22708439/3b987e70-ed44-11e6-856d-97932dc1a170.png">

**Comment by bernini** [comment]
@tenji240 Awesome that you got tips returned! I tried in Reddit using `Everything` and got the sidebar but no tips. Let me try to remove and re-install it and see if that works.

**Comment by bernini** [comment]
@tenji240 Reinstalling it worked! I got the sidebar in both Reddit and Gmail now. Exciting! Will close this case and will create a new one for improvements.
