### ISSUE TITLE
Chrome extension design

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#30]

**Comment by bernini** [comment]
Grammarly's is pretty complicated (involves a lightbox) but also seamless.
http://recordit.co/dG0jRBKi4n

**Comment by bernini** [comment]
## Choose style guide (in add-on bar)
![screen shot 2017-02-20 at 11 50 25 am](https://cloud.githubusercontent.com/assets/3891237/23134448/e044aebc-f762-11e6-9f26-426e08bd393c.png)

## Check writing
![screen shot 2017-02-20 at 11 50 40 am](https://cloud.githubusercontent.com/assets/3891237/23134451/e2de5790-f762-11e6-9c24-4cdc833e24c0.png)

## Tips screen
![screen shot 2017-02-20 at 11 53 56 am](https://cloud.githubusercontent.com/assets/3891237/23135561/2901827a-f767-11e6-9d2b-0b7fcdaa585d.png)

**Comment by bernini** [comment]
Waiting for research in #31. Once we know S/M/L estimates for the amount of work, we can decide which pieces we want to start with.

**Comment by bernini** [comment]
Elements for the extension:

- Ability to select a guide, including private style guide
- Visually differentiate text that matches a tip
- One-click replace for text (also handle `avoid altogether` and `FYI` tip types)
- Link to full guide on Irregardless (?)
- A way to clear a specific tip by ignoring it for that document
- Ability to toggle automatic checking vs. not
- Disable for certain sites

As part of this, we'll also need to handle long tip explanations (potentially with a scroll bar or expand functionality) and duplicate tips.

Main areas for selections/customization seem to be the 

1. toolbar icon
2. an icon in the writing area
3. a separate popup box

I'm experimenting with using the look & feel of the google docs plugin for the chrome extension. The placement of all the elements is TBD

![top style guide](https://cloud.githubusercontent.com/assets/3891237/26535529/515bf4a8-43fc-11e7-9157-b6fea866bbb4.png)

![writing example](https://cloud.githubusercontent.com/assets/3891237/26535532/5da8bd5e-43fc-11e7-815b-2d50a16040bc.png)

**Comment by bernini** [comment]
One question I'm weighing - should we repeat the flagged phrase in the tip card for clarity or not? It might add clarity, but it might be repetitive and also it makes the tip longer.

**Comment by bernini** [comment]
@johnweldon Just FYI that I'm starting to put some ideas in this case based on your feedback in #31. Would like to finalize functionality/placement within the next week.

**Comment by bernini** [comment]
@RedPenPal @johnweldon 
v1 of the spec is below. Feedback is very welcome, and I would love another set of eyes to see if this makes sense. (Wired up some of it in Invision, but I don't know that it actually helps to understand the flow: https://invis.io/ZFC08L26J)

There's a few more pieces to figure out but hopefully enough for John to get started.

## Phrase flagged
(Ignore the favicon in the Gmail compose box in these mocks - I decided not to take this approach but forgot to remove.)
![underlined phrase](https://cloud.githubusercontent.com/assets/3891237/26769959/f9b9cace-4980-11e7-86e4-f51b41dce9b8.png)


## Tip shown on hover
![replace tip type](https://cloud.githubusercontent.com/assets/3891237/26769963/010232d0-4981-11e7-8e5e-e3fe66d254a8.png)


## "Clear" appears on hover on ×
Let me know if "ignore" seems like the better CTA. I want to distinguish it from closing the tip card, so this might need some more iteration to make that clear.
![ignore hover](https://cloud.githubusercontent.com/assets/3891237/26769965/09f758de-4981-11e7-85e4-aca9413d1dd0.png)


## Click on tip phrase to view tip on Irregardless
![view tip on web](https://cloud.githubusercontent.com/assets/3891237/26769970/10bc5bce-4981-11e7-874e-4b48d3384c83.png)


## Click in icon in toolbar to choose style guide
![check writing on](https://cloud.githubusercontent.com/assets/3891237/26769973/16a8b3ca-4981-11e7-9965-7f21754b57af.png)


## Toggle off the writing checker
![check writing off](https://cloud.githubusercontent.com/assets/3891237/26769975/1a013876-4981-11e7-9085-4f143afacf8a.png)

**Comment by bernini** [comment]
Also, I took some of this from Google Docs plugin, so "Replace with:" should be "Instead try:" and we should remove the "Everything" style guide option.

**Comment by evertsd** [comment]
- This is _mostly_ done, the one thing I'd say remaining is that we're not showing author information on the tip atm
