### ISSUE TITLE
Add Chrome extension to app upsells

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#33]
"Try our Chrome extension"

- Web: https://irregardless.ly/upload?collection_id=11
- Email footer

**Comment by evertsd** [comment]
Investigate only showing for chrome (not too long)

**Comment by bernini** [comment]
It seems like sometimes the Chrome extension button doesn't show even when I'm on Chrome, so let's remove the logic.

**Comment by bernini** [comment]
Can't repro (always showing for me) so closing.
