### ISSUE TITLE
Apply styling to flagged text in Chrome

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#36]
**Ignore the favicon in the Gmail compose box** in these mocks - I decided not to take this approach but forgot to remove.
![underlined phrase](https://cloud.githubusercontent.com/assets/3891237/26769959/f9b9cace-4980-11e7-86e4-f51b41dce9b8.png)

**Comment by evertsd** [comment]
This is working now, highlight _may_ be slightly darker than desired, will demo 09/15
