### ISSUE TITLE
Add ability to turn on/off writing checker

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#41]
Show toggle to turn automatic writing check on and off. When it's off, change favicon to reflect that and remove all flagging from the text.

Toggle off the writing checker
![check writing off](https://cloud.githubusercontent.com/assets/3891237/26769975/1a013876-4981-11e7-9085-4f143afacf8a.png)

**Comment by evertsd** [comment]
Punt for now, intended use case in the future

Settings to have it off for specific sites.

**Comment by bernini** [comment]
For this version, we can just set it to toggle off/on (not be different for different sites).

**Comment by bernini** [comment]
@evertsd Functionality seems great. In the future, we may want to also change the icon so it's clear if it's on or off, but I can create a separate case for that.

I'll also create a case for the design follow up we discussed.
