### ISSUE TITLE
Add ability to access style guides from clicking favicon 

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#42]
Ideally we can repurpose existing the Google Docs style picker functionality here

Click in icon in toolbar to choose style guide
![check writing on](https://cloud.githubusercontent.com/assets/3891237/26769973/16a8b3ca-4981-11e7-9965-7f21754b57af.png)

**Comment by evertsd** [comment]
This is done, however the check writing is missing (will do for #41) and private guides are not yet functional (covered by #44)
