### ISSUE TITLE
Tip card location logic or placement

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#52]
Right now it's not very smart about where it displays, so this can happen (basically the tip card is off-screen when I view emails in the full screen view):

![screen shot 2017-09-17 at 11 42 53 pm](https://user-images.githubusercontent.com/3891237/30528546-1851f9d8-9c02-11e7-821c-07e5b60a769f.png)

I don't know how many people use the full-screen view or other configurations, but the simplest thing might be to put the card somewhere where it always works, i.e. left-aligned with the compose window. This will mean it will block text though, so we should discuss before you dive in to see what makes the most sense.

**Comment by evertsd** [comment]
For now just limiting the left location to be `>= 10px`
<img width="551" alt="screen shot 2017-09-18 at 9 14 45 pm" src="https://user-images.githubusercontent.com/903050/30572939-79ba8a8c-9cb6-11e7-9f40-611f1644d4a7.png">

**Comment by bernini** [comment]
I also ran into this situation, where the tip is actually stuck open. I'm feeling like we should do #54 soon too.

![image](https://user-images.githubusercontent.com/3891237/30838209-2d3ec312-a238-11e7-8d83-e4a332207ec5.png)

**Comment by bernini** [comment]
@evertsd Are you free to chat about this case and some of these Monday evening? I leave for my trip Tues night so want to make sure you're set while I'm gone.

**Comment by bernini** [comment]
SO nice, @evertsd. As we chatted about, let's add a bit more padding when the card is on the right before we close this out.

![screen shot 2017-12-05 at 9 29 53 pm](https://user-images.githubusercontent.com/3891237/33641434-80dec348-da03-11e7-8335-c90a2ad871d0.png)

**Comment by bernini** [comment]
👍
