### ISSUE TITLE
Add close button to style guide picker

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#59]
It may not be clear at first to click the icon or click outside the frame.

![image](https://user-images.githubusercontent.com/3891237/31698538-04b432e6-b38c-11e7-82c1-794e51a11ebf.png)

**Comment by evertsd** [comment]
This is just about done, I think :| button's added, but atm there's a bug w/what it closes

**Comment by bernini** [comment]
Closing this, follow up tweaks in #64
